name: Build VCV Rack Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up environment
      run: |
        echo "RACK_DIR=$PWD/Rack-SDK" >> $GITHUB_ENV
        echo "BUILD_FLAGS=-j$(nproc)" >> $GITHUB_ENV
      shell: bash

    - name: Build plugin
      run: make RACK_DIR=$RACK_DIR $BUILD_FLAGS
      shell: bash

    - name: Upload plugin binary (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: windows-plugin
        path: plugin.dll
        if-no-files-found: ignore

    - name: Upload plugin binary (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: linux-plugin
        path: plugin.so
        if-no-files-found: ignore

    - name: Upload plugin binary (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: macos-plugin
        path: plugin.dylib
        if-no-files-found: ignore
